// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5dR7AboiSs57yeqJE_Uc6ex8UkHBkAh0',
    appId: '1:757835389047:web:724a486ff19e45b15c4e72',
    messagingSenderId: '757835389047',
    projectId: 'chiaseanh2',
    authDomain: 'chiaseanh2.firebaseapp.com',
    storageBucket: 'chiaseanh2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCoAvkhWcBu85YwSfXDeUYdYLgwETjuLM',
    appId: '1:757835389047:android:a8106ae5fcd40d485c4e72',
    messagingSenderId: '757835389047',
    projectId: 'chiaseanh2',
    storageBucket: 'chiaseanh2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ECCam016zQ3IqijkB-AVazeZeqqthlk',
    appId: '1:757835389047:ios:fe76be715783f8035c4e72',
    messagingSenderId: '757835389047',
    projectId: 'chiaseanh2',
    storageBucket: 'chiaseanh2.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );
}
